---
engines:
  pylint:
    enabled: false
  pylintpython3:
    enabled: false

exclude_paths:
  - 'tests/**'
  - '**/*.md'
  - '**/__init__.py'
  - 'README.md'
  - 'yamlpath/func.py'  # Deprecated; the entire file is just relays
  - 'yamlpath/patches/**' # 3rd Party contributions
