# Test publishing to PyPI.
# @see:  https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Upload Python TEST Package

on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  validate:
    name: Code Quality Assessment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        ruby-version: ['3.4']

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run full test suite
      run: |
        bash run-tests.sh ${{ matrix.python-version }}

  publish:
    name: Publish to TEST PyPI
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: 'PyPI:  Test'
    needs: validate

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install Build Tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build setuptools wheel
    - name: Build Artifacts
      run: |
        sed -i -r -e "s/(^__version__[[:space:]]*=[[:space:]]*)("'"'"[[:digit:]](\.[[:digit:]])+)"'"'"/\1\2.RC$(date "+%Y%m%d%H%M%S")"'"'"/" yamlpath/__init__.py
        python -m build
    - name: Publish Artifacts
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        packages-dir: dist/
