# This workflow runs the full sweep of tests for the yamlpath package and publishes the coverage report to coveralls.io
name: Publish Coverage Report to Coveralls.IO

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: Install dependencies
        run: |
          ruby_constraints_file="requirements/test-tools/ruby-3.4.txt"
          if ! [ -f "$ruby_constraints_file" ]; then
            echo "ERROR: Expected Ruby dependency file not found: $ruby_constraints_file" >&2
            exit 1
          fi
          gem install --user-install --no-document -g "$ruby_constraints_file" --no-lock
          ruby_gem_user_bin="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
          echo "$ruby_gem_user_bin" >> "$GITHUB_PATH"
          "$ruby_gem_user_bin/eyaml" --version
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements/test-tools/python-3.12.txt
          python -m pip install --editable .
      - name: Unit Test with pytest
        run: |
          pytest --verbose --cov=yamlpath --cov-report=term-missing --cov-fail-under=100 --script-launch-mode=subprocess tests
      - name: Publish coveralls Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
